name: Monsterplugin
version: '${project.version}'
main: me.marc3308.monsterplugin.Monsterplugin
api-version: 1.19

commands:
  spinfo:
    description: info about spawn
    permission: op
  delwol:
    description: delets the world
    permission: op
  loadit:
    description: dont use
    permission: op
  givetime:
    description: dont use
    permission: op
  worldtimeset:
    description: sets the world time
    permission: op
  spielerinfo:
    description: get the player info log
    permission: parteleitung