name: Monsterplugin
version: '${project.version}'
main: me.marc3308.monsterplugin.Monsterplugin
depend: [zerotrust]
api-version: 1.19
permissions:
  technikdetails:
    description: allows to use technikdetails

commands:
  spinfo:
    description: info about spawn
    permission: technikdetails
  delwol:
    description: delets the world
    permission: op
  loadit:
    description: dont use
    permission: op
  givetime:
    description: dont use
    permission: technikdetails
  worldtimeset:
    description: sets the world time
    permission: technikdetails
  spielerinfo:
    description: get the info
    permission: technikdetails