name: Monsterplugin
version: '1.21.1'
main: me.marc3308.monsterplugin.Monsterplugin
depend: [zerotrust]
api-version: 1.21

permissions:
  technikdetails:
    description: allows to use technikdetails

commands:
  spiele:
    description: open game gui
    permission: technikdetails
  spinfo:
    description: info about spawn
    permission: technikdetails
  delwol:
    description: delets the world
    permission: op
  loadit:
    description: dont use
    permission: op
  givetime:
    description: dont use
    permission: technikdetails
  worldtimeset:
    description: sets the world time
    permission: technikdetails
  spielerinfo:
    description: get the info
    permission: technikdetails
  cosmetic:
    description: gives you a cosmetmenu
  cosmetics:
    description: gives you a cosmetik
    permission: technikdetails
  loadworldtomax:
    description: loads the world to max
    permission: op